controller_list:
  - name: fake_head_controller
    joints:
      - neck_axis_1
      - neck_axis_2
      - neck_axis_3
  - name: fake_left_arm_controller
    joints:
      - shoulder_left_axis_1
      - shoulder_left_axis_2
      - shoulder_left_axis_3
      - elbow_left
      - wrist_left
  - name: fake_right_arm_controller
    joints:
      - shoulder_right_axis_1
      - shoulder_right_axis_2
      - shoulder_right_axis_3
      - elbow_right
      - wrist_right